services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "18080:80"

  # gRPC server with reflection support for integration testing
  grpc-greeter:
    image: romk/grpc-helloworld-reflection
    ports:
      - "50051:50051"

  # GraphQL server for integration testing
  graphql:
    image: npalm/graphql-java-demo
    ports:
      - "14000:8080"
